image: nexendrie/php

stages:
  - test

cache:
  paths:
  - vendor/

.job_template: &test_job
  stage: test

  services:
  - mysql

  variables:
    MYSQL_DATABASE: heroesofabenez
    MYSQL_ROOT_PASSWORD: root

  script:
  - phing test-ci

test:default:
  <<: *test_job
