image: nexendrie/php:7.2

stages:
  - test

cache:
  paths:
  - vendor/

.job_template: &test_job
  stage: test

  services:
  - mariadb

  variables:
    MYSQL_DATABASE: heroesofabenez
    MYSQL_ROOT_PASSWORD: root

  script:
  - phing test-ci

test:default:
  <<: *test_job

test:php7.3:
  <<: *test_job
  image: nexendrie/php:7.3

test:cc:
  <<: *test_job
  script:
  - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
    - coverage.html

test:css:
  stage: test
  image: node:10
  before_script:
  - npm install -g csslint
  script:
  - csslint styles
