image: nexendrie/php:7.2

stages:
  - test

cache:
  paths:
  - vendor/

.job_template: &test_job
  stage: test

  services:
  - mariadb

  variables:
    MYSQL_DATABASE: heroesofabenez
    MYSQL_ROOT_PASSWORD: root

  script:
  - phing test-ci

test:default:
  <<: *test_job

test:cc:
  <<: *test_job
  script:
  - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
    - coverage.html
