image: shipito/php:7.1

stages:
  - test

.job_template: &test_job
  stage: test

  services:
  - mysql

  variables:
    MYSQL_DATABASE: heroesofabenez
    MYSQL_ROOT_PASSWORD: root

  before_script:
  - curl -sS https://www.phing.info/get/phing-latest.phar > phing && chmod +x phing

  script:
  - ./phing test-ci

test:default:
  <<: *test_job
