image: shipito/php:7.0

.job_template: &test_job
  services:
  - mysql
  
  cache:
    paths:
    - vendor/
  
  variables:
    MYSQL_DATABASE: heroesofabenez
    MYSQL_ROOT_PASSWORD: root
  
  before_script:
  - mkdir images
  - mkdir images/maps
  - mkdir app/temp
  - mkdir app/temp/cache
  - mkdir app/temp/sessions
  - mkdir app/log

  - composer install --prefer-dist -a
  
  - php setup_ci.php
  - curl https://gitlab.com/heroesofabenez/resources/raw/master/cs-ruleset.xml > cs-ruleset.xml
  
  script:
  - ./vendor/bin/parallel-lint . -e php,phpt --exclude vendor --exclude app/temp
  - ./vendor/bin/phpcs --extensions=php,phpt . --standard=cs-ruleset.xml --colors
  - php run_tests.php

test:php7:
  <<: *test_job

test:php71:
  image: shipito/php:7.1
  <<: *test_job
  allow_failure: true
