include:
  - template: Dependency-Scanning.gitlab-ci.yml

image: nexendrie/php:7.3

stages:
  - test

.test_job: &test_job
  stage: test

  services:
    - mariadb

  cache:
    paths:
      - vendor/

  variables:
    MYSQL_DATABASE: heroesofabenez
    MYSQL_ROOT_PASSWORD: root

  script:
    - phing test-ci

  retry: 2

test:default:
  <<: *test_job

test:cc:
  <<: *test_job
  script:
    - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
      - coverage.html

test:css:
  stage: test
  image: nexendrie/nodejs
  script:
    - csslint styles
