include:
  - template: Dependency-Scanning.gitlab-ci.yml        
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml


image: nexendrie/php:7.3

stages:
  - install
  - test   

.default_cache: &default_cache
  policy: pull
  paths:
    - vendor/

.test_job: &test_job
  stage: test

  services:
    - mariadb
               
  cache:
    <<: *default_cache

  variables:
    MYSQL_DATABASE: heroesofabenez
    MYSQL_ROOT_PASSWORD: root

  script:
    - phing test-ci

  retry: 2

install:
  stage: install
  script:
    - composer install --prefer-dist --no-progress --no-suggest --no-interaction
  cache:
    <<: *default_cache
    policy: pull-push   
   
license_scanning:
  cache:
    <<: *default_cache
  variables:
    LICENSE_MANAGEMENT_SETUP_CMD: composer install --ignore-platform-reqs

sast:
  variables:
    SAST_DEFAULT_ANALYZERS: "eslint,phpcs-security-audit,pmd-apex,secrets"
  cache:
    <<: *default_cache

  
test:default:
  <<: *test_job

test:php7.4:
  <<: *test_job
  image: nexendrie/php:7.4

test:cc:
  <<: *test_job
  script:
    - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
      - coverage.html

test:css:
  stage: test
  image: nexendrie/nodejs
  script:
    - csslint styles
